/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibeRouteImport } from './routes/vibe'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CollabsRouteImport } from './routes/collabs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TalentUsernameRouteImport } from './routes/talent.$username'
import { Route as CollabsSlugRouteImport } from './routes/collabs.$slug'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminChatRouteImport } from './routes/admin.chat'

const VibeRoute = VibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabsRoute = CollabsRouteImport.update({
  id: '/collabs',
  path: '/collabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TalentUsernameRoute = TalentUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => TalentRoute,
} as any)
const CollabsSlugRoute = CollabsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollabsRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collabs': typeof CollabsRouteWithChildren
  '/events': typeof EventsRoute
  '/milestones': typeof MilestonesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/reserve': typeof ReserveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/talent': typeof TalentRouteWithChildren
  '/vibe': typeof VibeRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/collabs/$slug': typeof CollabsSlugRoute
  '/talent/$username': typeof TalentUsernameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collabs': typeof CollabsRouteWithChildren
  '/events': typeof EventsRoute
  '/milestones': typeof MilestonesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/reserve': typeof ReserveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/talent': typeof TalentRouteWithChildren
  '/vibe': typeof VibeRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/collabs/$slug': typeof CollabsSlugRoute
  '/talent/$username': typeof TalentUsernameRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collabs': typeof CollabsRouteWithChildren
  '/events': typeof EventsRoute
  '/milestones': typeof MilestonesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/reserve': typeof ReserveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/talent': typeof TalentRouteWithChildren
  '/vibe': typeof VibeRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/collabs/$slug': typeof CollabsSlugRoute
  '/talent/$username': typeof TalentUsernameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/collabs'
    | '/events'
    | '/milestones'
    | '/products'
    | '/profile'
    | '/recap'
    | '/reserve'
    | '/sitemap.xml'
    | '/sos'
    | '/talent'
    | '/vibe'
    | '/admin/chat'
    | '/admin/payments'
    | '/admin/reservations'
    | '/collabs/$slug'
    | '/talent/$username'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/chat'
    | '/collabs'
    | '/events'
    | '/milestones'
    | '/products'
    | '/profile'
    | '/recap'
    | '/reserve'
    | '/sitemap.xml'
    | '/sos'
    | '/talent'
    | '/vibe'
    | '/admin/chat'
    | '/admin/payments'
    | '/admin/reservations'
    | '/collabs/$slug'
    | '/talent/$username'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/collabs'
    | '/events'
    | '/milestones'
    | '/products'
    | '/profile'
    | '/recap'
    | '/reserve'
    | '/sitemap.xml'
    | '/sos'
    | '/talent'
    | '/vibe'
    | '/admin/chat'
    | '/admin/payments'
    | '/admin/reservations'
    | '/collabs/$slug'
    | '/talent/$username'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CollabsRoute: typeof CollabsRouteWithChildren
  EventsRoute: typeof EventsRoute
  MilestonesRoute: typeof MilestonesRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RecapRoute: typeof RecapRoute
  ReserveRoute: typeof ReserveRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SosRoute: typeof SosRoute
  TalentRoute: typeof TalentRouteWithChildren
  VibeRoute: typeof VibeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibe': {
      id: '/vibe'
      path: '/vibe'
      fullPath: '/vibe'
      preLoaderRoute: typeof VibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collabs': {
      id: '/collabs'
      path: '/collabs'
      fullPath: '/collabs'
      preLoaderRoute: typeof CollabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/talent/$username': {
      id: '/talent/$username'
      path: '/$username'
      fullPath: '/talent/$username'
      preLoaderRoute: typeof TalentUsernameRouteImport
      parentRoute: typeof TalentRoute
    }
    '/collabs/$slug': {
      id: '/collabs/$slug'
      path: '/$slug'
      fullPath: '/collabs/$slug'
      preLoaderRoute: typeof CollabsSlugRouteImport
      parentRoute: typeof CollabsRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollabsRouteChildren {
  CollabsSlugRoute: typeof CollabsSlugRoute
}

const CollabsRouteChildren: CollabsRouteChildren = {
  CollabsSlugRoute: CollabsSlugRoute,
}

const CollabsRouteWithChildren =
  CollabsRoute._addFileChildren(CollabsRouteChildren)

interface TalentRouteChildren {
  TalentUsernameRoute: typeof TalentUsernameRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentUsernameRoute: TalentUsernameRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CollabsRoute: CollabsRouteWithChildren,
  EventsRoute: EventsRoute,
  MilestonesRoute: MilestonesRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RecapRoute: RecapRoute,
  ReserveRoute: ReserveRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SosRoute: SosRoute,
  TalentRoute: TalentRouteWithChildren,
  VibeRoute: VibeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
